inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/services/technical_metadata_generator_spec.rb'
    - 'spec/services/file_identifier_service_spec.rb'
    - 'spec/services/moab_processing_service_spec.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/services/av_characterizer_service.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/services/av_characterizer_service.rb'
    - 'app/services/technical_metadata_generator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/av_characterizer_service.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/services/av_characterizer_service.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/av_characterizer_service.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false