inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - bin/bundle
    - vendor/**/*

Layout/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Rails/FilePath:
  EnforcedStyle: arguments
