services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      DATABASE_NAME: technical_metadata
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: sekret
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      RAILS_LOG_TO_STDOUT: "true"
      REDIS_URL: redis://redis:6379/
      SETTINGS__REDIS_URL: redis://redis:6379/
    volumes:
       - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db
      - workers
  workers:
    platform: linux/amd64 # Required for running on Apple Silicon
    build:
      context: .
      dockerfile: docker/workers/Dockerfile
    environment:
      DATABASE_NAME: technical_metadata
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: sekret
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      RAILS_LOG_TO_STDOUT: "true"
      REDIS_URL: redis://redis:6379/
      SETTINGS__REDIS_URL: redis://redis:6379/
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
