version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.2.3
workflows:
  build:
    jobs:
      - ruby-rails/validate-api:
          name: validate
      - ruby-rails/lint:
          name: lint
      - ruby-rails/lint-erb
      - ruby-rails/test-rails:
          name: test
      - ruby-rails/docker-publish:
          context: dlss
          dockerfile: docker/app/Dockerfile
          name: publish-latest
          image: suldlss/technical-metadata-service
          requires:
            - validate
            - lint
            - test
          filters:
            branches:
              only:
                - main
