dor_services:
  url: http://localhost:3003
  token: TOKEN_GOES_HERE # for token see https://github.com/sul-dlss/dor-services-app#authentication

hmac_secret: 'my$ecretK3y'

storage_root_map: # empty here, override in #{RAILS_ENV}.yml
  default: {}

redis_url: redis://localhost:6379/
